### ISSUE TITLE
Library symlinks not installed

### ISSUE THREAD

**Issue by hramrach** [fbuihuu/libtree#1]
Only the shared library is installed, not the symlinks that allow linking to it.

While it might be possible to create these symlinks with some system tool the makefile does not do it making the library unlinkable and unpackagable.

hmm, install can't install symlinks so here is a different patch https://github.com/hramrach/libtree/commit/2d948f85e2313c043820f5c946b251c6e2358909

**Comment by fbuihuu** [comment]
libtree.so symlink seems to be missing indeed.

However libtree.so.0 should be created by ldconfig, I think.

**Comment by hramrach** [comment]
And where does the makefile call ldconfig to create the symlink?

If the link is created in the build directory to allow linking the not yet installed library it should be created in the install target too.

**Comment by fbuihuu** [comment]
The build directory is definitely not a usual place that ldconfig can spot, however the installation path is. And the usual thing to do after a lib installation is to call ldconfig, primarly to update its cache.

**Comment by hramrach** [comment]
Yes, it works for me when the makefile only makes the .so link, the so.0 link is created by dpkg.

Thanks

**Comment by hramrach** [comment]
why is this closed?

I don't see a code change fixing this.

**Comment by fbuihuu** [comment]
I just pushed some changes including the creation of .so during installation.

Can I close this issue now ?

**Comment by hramrach** [comment]
sure, thanks :)
