### ISSUE TITLE
inserting 1536452766 2219981191 2013842191 206515713 3973769363 breaks bstree and splay tree

### ISSUE THREAD

**Issue by hramrach** [fbuihuu/libtree#4]
<-  1536452766
     1536452766 <-  2219981191
     1536452766     2219981191 <-  2013842191
     1536452766     2013842191     2219981191 <-   206515713
      206515713     1536452766     2013842191     2219981191 <-  3973769363
      206515713     1536452766     2013842191     2219981191     3973769363
bs tree: item 0 (3973769363) != 206515713
inserted items:
     1536452766     2219981191     2013842191      206515713     3973769363
Aborted

 <-  1536452766
     1536452766 <-  2219981191
     1536452766     2219981191 <-  2013842191
     1536452766     2013842191     2219981191 <-   206515713
      206515713     1536452766     2013842191     2219981191 <-  3973769363
      206515713     1536452766     2013842191     2219981191     3973769363
splay tree: item 0 (3973769363) != 206515713
inserted items:
     1536452766     2219981191     2013842191      206515713     3973769363

The sequence for avl and rb tree is longer but again the last inserted item appears first:

 1536452766 2219981191 2013842191 206515713 3973769363 2195571548 1470591614 99517740 3346335896 1968000334 2824163306 825862710 593949289 3087228942 9464287 3502443898 1825977738 4200665288

 <-  1536452766
     1536452766 <-  2219981191
     1536452766     2219981191 <-  2013842191
     1536452766     2013842191     2219981191 <-   206515713
      206515713     1536452766     2013842191     2219981191 <-  3973769363
      206515713     1536452766     2013842191     2219981191     3973769363 <-  2195571548
      206515713     1536452766     2013842191     2195571548     2219981191     3973769363 <-  1470591614
      206515713     1470591614     1536452766     2013842191     2195571548     2219981191     3973769363 <-    99517740
       99517740      206515713     1470591614     1536452766     2013842191     2195571548     2219981191     3973769363 <-  3346335896
       99517740      206515713     1470591614     1536452766     2013842191     2195571548     2219981191     3346335896     3973769363 <-  1968000334
       99517740      206515713     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     3346335896     3973769363 <-  2824163306
       99517740      206515713     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3346335896     3973769363 <-   825862710
       99517740      206515713      825862710     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3346335896     3973769363 <-   593949289
       99517740      206515713      593949289      825862710     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3346335896     3973769363 <-  3087228942
       99517740      206515713      593949289      825862710     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3087228942     3346335896     3973769363 <-     9464287
        9464287       99517740      206515713      593949289      825862710     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3087228942     3346335896     3973769363 <-  3502443898
        9464287       99517740      206515713      593949289      825862710     1470591614     1536452766     1968000334     2013842191     2195571548     2219981191     2824163306     3087228942     3346335896     3502443898     3973769363 <-  1825977738
        9464287       99517740      206515713      593949289      825862710     1470591614     1536452766     1825977738     1968000334     2013842191     2195571548     2219981191     2824163306     3087228942     3346335896     3502443898     3973769363 <-  4200665288
        9464287       99517740      206515713      593949289      825862710     1470591614     1536452766     1825977738     1968000334     2013842191     2195571548     2219981191     2824163306     3087228942     3346335896     3502443898     3973769363     4200665288
avl tree: item 0 (4200665288) != 9464287
inserted items:
     1536452766     2219981191     2013842191      206515713     3973769363     2195571548     1470591614       99517740     3346335896     1968000334     2824163306      825862710      593949289     3087228942        9464287     3502443898     1825977738     4200665288
Aborted

**Comment by fbuihuu** [comment]
will look at this later.

Please don't open multiple ticket for the same issue: #3 and this one are the same.

**Comment by hramrach** [comment]
While this is a particular bug I hope that in the future the library would include a piece of sample code that would demonstrate how to use the library and demonstrate the library works, which is issue #3

**Comment by hramrach** [comment]
This is due to bug in my comparison function.

I used the sample function from the readme but it dies not work on unsigned keys.
