### ISSUE TITLE
license problematic

### ISSUE THREAD

**Issue by shawnl** [fbuihuu/libtree#7]
COPYING says LGPL 2.1, source files say Library general public license 2 (a license that does not exist, see http://www.gnu.org/licenses/old-licenses/old-licenses.html#LGPL). This is a problem

Do you mean to license under LGPL 2.1+, if so, change the headers of your source files to the fallowing:

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

**Comment by richardfontana** [comment]
There is a GNU Library General Public License 2, but I agree there is a discrepancy here in that the license file is LGPLv2.1 and there are LGPLv2 source file notices.

Moreover the absence of "or any later version" in the source file license notices may cause some concerns about license incompatibility. I am aware of an LGPLv3-or-later project using some of these source files; while it is possible to reason away the appearance of a license conflict it should not have to be necessary.

I support the recommendation of @shawnl to change the source file license notices to LGPLv2.1+.

**Comment by fbuihuu** [comment]
Source code has been clarified and libtree is now using LGPLv2.1+.
Thanks and sorry for the loooong delay.
